"""Type stubs for gmdbuilder.core"""

from typing import Any, Literal, TypeVar, TypeGuard, overload

from gmdkit.models.object import Object as KitObject
from gmdbuilder.object_types import ObjectType
import gmdbuilder.object_types as td

T = TypeVar("T", bound=ObjectType)

def is_obj_type(obj: ObjectType, obj_type: type[T]) -> TypeGuard[T]:
    """Type-narrows obj to a specific TypedDict type by matching its ID."""


class Object(dict[str, Any]):
    """
    Note: Not for users to call directly.
    
    The actual dict implementation hidden behind the ObjectType TypedDict.
    
    This is to intercept & validate mutations of objects and add new helpers.
    """
    _obj_id: int
    __slots__: tuple[str]
    
    def __init__(self, obj_id: int) -> None: ...
    def __setitem__(self, k: str, v: Any) -> None: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    
    @staticmethod
    def wrap_object(obj: ObjectType | Object) -> ObjectType: ...


def _to_raw_key_cached(key: str) -> int | str: ...
def to_kit_object(obj: ObjectType) -> KitObject:
    """
    Convert object typeddict to gmdkit object dict.
    
    Example:
        {a1: 900, a2: 50, a57: {2}} → {1: 900, 2: 50, 57: IDList([2])}
    """


def _from_raw_key_cached(key: object) -> str: ...
def from_kit_object(obj: dict[int | str, Any]) -> ObjectType:
    """
    Convert gmdkit object dict to object typeddict.
    
    Example:
        {1: 900, 2: 50, 57: IDList([2])} → {a1: 900, a2: 50, a57: {2}}
    """



@overload
def is_obj_id(obj: ObjectType, object_id: Literal[10]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[11]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[12]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[13]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[20]) -> TypeGuard[td.TimewarpType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[22]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[23]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[24]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[25]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[26]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[27]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[28]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[31]) -> TypeGuard[td.StartposType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[32]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[33]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[35]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[36]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[40]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[45]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[46]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[47]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[55]) -> TypeGuard[td.EnterPresetType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[56]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[57]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[58]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[59]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[67]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[71]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[84]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[85]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[86]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[87]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[88]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[89]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[97]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[98]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[99]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[101]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[111]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[137]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[138]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[139]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[140]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[141]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[154]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[155]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[156]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[162]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[180]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[181]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[182]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[183]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[184]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[185]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[186]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[187]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[188]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[200]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[201]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[202]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[203]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[205]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[222]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[223]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[224]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[286]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[287]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[375]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[376]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[377]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[378]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[394]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[395]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[396]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[397]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[398]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[399]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[660]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[678]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[679]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[680]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[740]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[741]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[742]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[745]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[747]) -> TypeGuard[td.PortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[899]) -> TypeGuard[td.ColorType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[901]) -> TypeGuard[td.MoveType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[914]) -> TypeGuard[td.TextType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[920]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[921]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[922]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[923]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[924]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[997]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[998]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[999]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1000]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1006]) -> TypeGuard[td.PulseType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1007]) -> TypeGuard[td.AlphaType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1019]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1020]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1021]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1022]) -> TypeGuard[td.OrbSawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1049]) -> TypeGuard[td.ToggleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1050]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1051]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1052]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1053]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1054]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1055]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1056]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1057]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1058]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1059]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1060]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1061]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1268]) -> TypeGuard[td.SpawnType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1275]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1329]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1330]) -> TypeGuard[td.OrbSawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1331]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1332]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1333]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1334]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1346]) -> TypeGuard[td.RotateType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1347]) -> TypeGuard[td.FollowType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1516]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1518]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1519]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1520]) -> TypeGuard[td.ShakeType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1521]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1522]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1523]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1524]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1525]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1526]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1527]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1528]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1582]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1583]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1585]) -> TypeGuard[td.AnimateType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1587]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1589]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1591]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1592]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1593]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1594]) -> TypeGuard[td.ToggleBlockType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1595]) -> TypeGuard[td.TouchType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1598]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1611]) -> TypeGuard[td.CountType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1612]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1613]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1614]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1615]) -> TypeGuard[td.ItemLabelType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1616]) -> TypeGuard[td.StopType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1618]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1619]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1620]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1697]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1698]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1699]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1704]) -> TypeGuard[td.DashType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1705]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1706]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1707]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1708]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1709]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1710]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1734]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1735]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1736]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1751]) -> TypeGuard[td.DashType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1752]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1755]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1811]) -> TypeGuard[td.InstantCountType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1812]) -> TypeGuard[td.OnDeathType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1813]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1814]) -> TypeGuard[td.FollowPlayerYType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1815]) -> TypeGuard[td.CollisionType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1816]) -> TypeGuard[td.CollisionBlockType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1817]) -> TypeGuard[td.PickupType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1818]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1819]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1829]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1831]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1832]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1833]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1834]) -> TypeGuard[td.SawType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1839]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1840]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1841]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1842]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1849]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1850]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1851]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1852]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1853]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1854]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1855]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1856]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1857]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1858]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1859]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1860]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1912]) -> TypeGuard[td.RandomType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1913]) -> TypeGuard[td.ZoomCameraType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1914]) -> TypeGuard[td.StaticCameraType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1915]) -> TypeGuard[td.EnterPresetType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1916]) -> TypeGuard[td.OffsetCameraType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1917]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1932]) -> TypeGuard[td.PlayerControlType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1933]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1934]) -> TypeGuard[td.SongType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1935]) -> TypeGuard[td.TimewarpType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1936]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1937]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1938]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[1939]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2015]) -> TypeGuard[td.RotateCameraType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2016]) -> TypeGuard[td.CameraGuideType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2020]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2021]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2022]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2023]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2024]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2025]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2026]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2027]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2028]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2029]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2030]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2031]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2032]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2033]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2034]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2035]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2036]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2037]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2038]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2039]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2040]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2041]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2042]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2043]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2044]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2045]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2046]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2047]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2048]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2049]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2050]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2051]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2052]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2053]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2054]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2055]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2062]) -> TypeGuard[td.CameraEdgeType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2063]) -> TypeGuard[td.CheckpointType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2064]) -> TypeGuard[td.TeleportType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2065]) -> TypeGuard[td.ParticleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2066]) -> TypeGuard[td.GravityType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2067]) -> TypeGuard[td.ScaleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2068]) -> TypeGuard[td.AdvRandomType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2069]) -> TypeGuard[td.ForceBlockType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2605]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2629]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2630]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2694]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2864]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2865]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2866]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2867]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2868]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2869]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2870]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2871]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2872]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2873]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2874]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2875]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2876]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2877]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2878]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2879]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2880]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2881]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2882]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2883]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2884]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2885]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2886]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2887]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2888]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2889]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2890]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2891]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2892]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2893]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2894]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2895]) -> TypeGuard[td.TemplateType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2896]) -> TypeGuard[td.TemplateType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2897]) -> TypeGuard[td.TemplateType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2899]) -> TypeGuard[td.OptionsType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2900]) -> TypeGuard[td.ArrowType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2901]) -> TypeGuard[td.GameplayOffsetType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2902]) -> TypeGuard[td.PortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2903]) -> TypeGuard[td.GradientType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2904]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2905]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2907]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2909]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2910]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2911]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2912]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2913]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2914]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2915]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2916]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2917]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2919]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2920]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2921]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2922]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2923]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2924]) -> TypeGuard[td.ShaderType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2925]) -> TypeGuard[td.CameraModeType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2926]) -> TypeGuard[td.GamemodePortalType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[2999]) -> TypeGuard[td.MgEditType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3000]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3001]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3002]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3004]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3005]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3006]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3007]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3008]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3009]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3010]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3011]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3012]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3013]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3014]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3015]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3016]) -> TypeGuard[td.AdvFollowType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3017]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3018]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3019]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3020]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3021]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3022]) -> TypeGuard[td.TeleportType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3023]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3024]) -> TypeGuard[td.EffectType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3027]) -> TypeGuard[td.TeleportType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3029]) -> TypeGuard[td.ChangeBgType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3030]) -> TypeGuard[td.ChangeGrType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3031]) -> TypeGuard[td.ChangeMgType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3032]) -> TypeGuard[td.KeyframeType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3033]) -> TypeGuard[td.AnimateKeyframeType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3119]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3120]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3121]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3219]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3303]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3304]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3482]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3483]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3484]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3492]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3493]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3600]) -> TypeGuard[td.EndType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3601]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3602]) -> TypeGuard[td.SfxType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3603]) -> TypeGuard[td.SfxType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3604]) -> TypeGuard[td.EventType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3605]) -> TypeGuard[td.SongType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3606]) -> TypeGuard[td.TriggerType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3607]) -> TypeGuard[td.SequenceType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3608]) -> TypeGuard[td.SpawnParticleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3609]) -> TypeGuard[td.InstantCollisionType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3612]) -> TypeGuard[td.MgSpeedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3613]) -> TypeGuard[td.UiType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3614]) -> TypeGuard[td.TimeType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3615]) -> TypeGuard[td.TimeEventType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3617]) -> TypeGuard[td.TimeControlType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3618]) -> TypeGuard[td.ResetType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3619]) -> TypeGuard[td.ItemEditType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3620]) -> TypeGuard[td.ItemCompareType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3640]) -> TypeGuard[td.StateBlockType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3641]) -> TypeGuard[td.ItemPersistType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3642]) -> TypeGuard[td.BpmType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3643]) -> TypeGuard[td.ToggleBlockType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3645]) -> TypeGuard[td.ForceBlockType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3660]) -> TypeGuard[td.EditAdvFollowType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3661]) -> TypeGuard[td.EditAdvFollowType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[3662]) -> TypeGuard[td.LinkVisibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4211]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4300]) -> TypeGuard[td.AnimatedType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4401]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4402]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4403]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4404]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4405]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4406]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4407]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4408]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4409]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4410]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4411]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4412]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4413]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4414]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4415]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4416]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4417]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4418]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4419]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4420]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4421]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4422]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4423]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4424]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4425]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4426]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4427]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4428]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4429]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4430]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4431]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4432]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4433]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4434]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4435]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4436]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4437]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4438]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4439]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4440]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4441]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4442]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4443]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4444]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4445]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4446]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4447]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4448]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4449]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4450]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4451]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4452]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4453]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4454]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4455]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4456]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4457]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4458]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4459]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4460]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4461]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4462]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4463]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4464]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4465]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4466]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4467]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4468]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4469]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4470]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4471]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4472]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4473]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4474]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4475]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4476]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4477]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4478]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4479]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4480]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4481]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4482]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4483]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4484]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4485]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4486]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4487]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4488]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4489]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4490]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4491]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4492]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4493]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4494]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4495]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4496]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4497]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4498]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4499]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4500]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4501]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4502]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4503]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4504]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4505]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4506]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4507]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4508]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4509]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4510]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4511]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4512]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4513]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4514]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4515]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4516]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4517]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4518]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4519]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4520]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4521]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4522]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4523]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4524]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4525]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4526]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4527]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4528]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4529]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4530]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4531]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4532]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4533]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4534]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4535]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4536]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4537]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4538]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: Literal[4539]) -> TypeGuard[td.CollectibleType]: ...
@overload
def is_obj_id(obj: ObjectType, object_id: int) -> bool:
    """Checks if the object has the given object ID. (adds type information)"""



@overload
def from_object_string(obj_string: str) -> ObjectType: ...
@overload
def from_object_string(obj_string: str, *, obj_type: type[T]) -> T: ...
@overload
def new_obj(object_id: Literal[10]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[11]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[12]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[13]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[20]) -> td.TimewarpType: ...
@overload
def new_obj(object_id: Literal[22]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[23]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[24]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[25]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[26]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[27]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[28]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[31]) -> td.StartposType: ...
@overload
def new_obj(object_id: Literal[32]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[33]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[35]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[36]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[40]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[45]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[46]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[47]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[55]) -> td.EnterPresetType: ...
@overload
def new_obj(object_id: Literal[56]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[57]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[58]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[59]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[67]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[71]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[84]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[85]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[86]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[87]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[88]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[89]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[97]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[98]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[99]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[101]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[111]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[137]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[138]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[139]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[140]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[141]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[154]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[155]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[156]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[162]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[180]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[181]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[182]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[183]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[184]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[185]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[186]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[187]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[188]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[200]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[201]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[202]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[203]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[205]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[222]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[223]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[224]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[286]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[287]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[375]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[376]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[377]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[378]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[394]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[395]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[396]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[397]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[398]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[399]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[660]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[678]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[679]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[680]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[740]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[741]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[742]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[745]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[747]) -> td.PortalType: ...
@overload
def new_obj(object_id: Literal[899]) -> td.ColorType: ...
@overload
def new_obj(object_id: Literal[901]) -> td.MoveType: ...
@overload
def new_obj(object_id: Literal[914]) -> td.TextType: ...
@overload
def new_obj(object_id: Literal[920]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[921]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[922]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[923]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[924]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[997]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[998]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[999]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1000]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1006]) -> td.PulseType: ...
@overload
def new_obj(object_id: Literal[1007]) -> td.AlphaType: ...
@overload
def new_obj(object_id: Literal[1019]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1020]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1021]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1022]) -> td.OrbSawType: ...
@overload
def new_obj(object_id: Literal[1049]) -> td.ToggleType: ...
@overload
def new_obj(object_id: Literal[1050]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1051]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1052]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1053]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1054]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1055]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1056]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1057]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1058]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1059]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1060]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1061]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1268]) -> td.SpawnType: ...
@overload
def new_obj(object_id: Literal[1275]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[1329]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1330]) -> td.OrbSawType: ...
@overload
def new_obj(object_id: Literal[1331]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[1332]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1333]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1334]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1346]) -> td.RotateType: ...
@overload
def new_obj(object_id: Literal[1347]) -> td.FollowType: ...
@overload
def new_obj(object_id: Literal[1516]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1518]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1519]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1520]) -> td.ShakeType: ...
@overload
def new_obj(object_id: Literal[1521]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1522]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1523]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1524]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1525]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1526]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1527]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1528]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1582]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1583]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1585]) -> td.AnimateType: ...
@overload
def new_obj(object_id: Literal[1587]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[1589]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[1591]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1592]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1593]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1594]) -> td.ToggleBlockType: ...
@overload
def new_obj(object_id: Literal[1595]) -> td.TouchType: ...
@overload
def new_obj(object_id: Literal[1598]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[1611]) -> td.CountType: ...
@overload
def new_obj(object_id: Literal[1612]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1613]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1614]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[1615]) -> td.ItemLabelType: ...
@overload
def new_obj(object_id: Literal[1616]) -> td.StopType: ...
@overload
def new_obj(object_id: Literal[1618]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1619]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1620]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1697]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1698]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1699]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1704]) -> td.DashType: ...
@overload
def new_obj(object_id: Literal[1705]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1706]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1707]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1708]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1709]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1710]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1734]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1735]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1736]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1751]) -> td.DashType: ...
@overload
def new_obj(object_id: Literal[1752]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1755]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1811]) -> td.InstantCountType: ...
@overload
def new_obj(object_id: Literal[1812]) -> td.OnDeathType: ...
@overload
def new_obj(object_id: Literal[1813]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1814]) -> td.FollowPlayerYType: ...
@overload
def new_obj(object_id: Literal[1815]) -> td.CollisionType: ...
@overload
def new_obj(object_id: Literal[1816]) -> td.CollisionBlockType: ...
@overload
def new_obj(object_id: Literal[1817]) -> td.PickupType: ...
@overload
def new_obj(object_id: Literal[1818]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1819]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1829]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1831]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1832]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1833]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1834]) -> td.SawType: ...
@overload
def new_obj(object_id: Literal[1839]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1840]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1841]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1842]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1849]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1850]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1851]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1852]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1853]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1854]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1855]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1856]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1857]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1858]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1859]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1860]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1912]) -> td.RandomType: ...
@overload
def new_obj(object_id: Literal[1913]) -> td.ZoomCameraType: ...
@overload
def new_obj(object_id: Literal[1914]) -> td.StaticCameraType: ...
@overload
def new_obj(object_id: Literal[1915]) -> td.EnterPresetType: ...
@overload
def new_obj(object_id: Literal[1916]) -> td.OffsetCameraType: ...
@overload
def new_obj(object_id: Literal[1917]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[1932]) -> td.PlayerControlType: ...
@overload
def new_obj(object_id: Literal[1933]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[1934]) -> td.SongType: ...
@overload
def new_obj(object_id: Literal[1935]) -> td.TimewarpType: ...
@overload
def new_obj(object_id: Literal[1936]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1937]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1938]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[1939]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2015]) -> td.RotateCameraType: ...
@overload
def new_obj(object_id: Literal[2016]) -> td.CameraGuideType: ...
@overload
def new_obj(object_id: Literal[2020]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2021]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2022]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2023]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2024]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2025]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2026]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2027]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2028]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2029]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2030]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2031]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2032]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2033]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2034]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2035]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2036]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2037]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2038]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2039]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2040]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2041]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2042]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2043]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2044]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2045]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2046]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2047]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2048]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2049]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2050]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2051]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2052]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2053]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2054]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2055]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2062]) -> td.CameraEdgeType: ...
@overload
def new_obj(object_id: Literal[2063]) -> td.CheckpointType: ...
@overload
def new_obj(object_id: Literal[2064]) -> td.TeleportType: ...
@overload
def new_obj(object_id: Literal[2065]) -> td.ParticleType: ...
@overload
def new_obj(object_id: Literal[2066]) -> td.GravityType: ...
@overload
def new_obj(object_id: Literal[2067]) -> td.ScaleType: ...
@overload
def new_obj(object_id: Literal[2068]) -> td.AdvRandomType: ...
@overload
def new_obj(object_id: Literal[2069]) -> td.ForceBlockType: ...
@overload
def new_obj(object_id: Literal[2605]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2629]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2630]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2694]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2864]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2865]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2866]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[2867]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2868]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2869]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2870]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2871]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2872]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2873]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2874]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2875]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2876]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2877]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2878]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2879]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2880]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2881]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2882]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2883]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2884]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2885]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2886]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2887]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2888]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2889]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2890]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2891]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2892]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2893]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2894]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[2895]) -> td.TemplateType: ...
@overload
def new_obj(object_id: Literal[2896]) -> td.TemplateType: ...
@overload
def new_obj(object_id: Literal[2897]) -> td.TemplateType: ...
@overload
def new_obj(object_id: Literal[2899]) -> td.OptionsType: ...
@overload
def new_obj(object_id: Literal[2900]) -> td.ArrowType: ...
@overload
def new_obj(object_id: Literal[2901]) -> td.GameplayOffsetType: ...
@overload
def new_obj(object_id: Literal[2902]) -> td.PortalType: ...
@overload
def new_obj(object_id: Literal[2903]) -> td.GradientType: ...
@overload
def new_obj(object_id: Literal[2904]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2905]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2907]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2909]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2910]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2911]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2912]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2913]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2914]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2915]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2916]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2917]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2919]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2920]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2921]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2922]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2923]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2924]) -> td.ShaderType: ...
@overload
def new_obj(object_id: Literal[2925]) -> td.CameraModeType: ...
@overload
def new_obj(object_id: Literal[2926]) -> td.GamemodePortalType: ...
@overload
def new_obj(object_id: Literal[2999]) -> td.MgEditType: ...
@overload
def new_obj(object_id: Literal[3000]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3001]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3002]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3004]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[3005]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[3006]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3007]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3008]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3009]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3010]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3011]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3012]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3013]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3014]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3015]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3016]) -> td.AdvFollowType: ...
@overload
def new_obj(object_id: Literal[3017]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3018]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3019]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3020]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3021]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3022]) -> td.TeleportType: ...
@overload
def new_obj(object_id: Literal[3023]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3024]) -> td.EffectType: ...
@overload
def new_obj(object_id: Literal[3027]) -> td.TeleportType: ...
@overload
def new_obj(object_id: Literal[3029]) -> td.ChangeBgType: ...
@overload
def new_obj(object_id: Literal[3030]) -> td.ChangeGrType: ...
@overload
def new_obj(object_id: Literal[3031]) -> td.ChangeMgType: ...
@overload
def new_obj(object_id: Literal[3032]) -> td.KeyframeType: ...
@overload
def new_obj(object_id: Literal[3033]) -> td.AnimateKeyframeType: ...
@overload
def new_obj(object_id: Literal[3119]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3120]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3121]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3219]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3303]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3304]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3482]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3483]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3484]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3492]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3493]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[3600]) -> td.EndType: ...
@overload
def new_obj(object_id: Literal[3601]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[3602]) -> td.SfxType: ...
@overload
def new_obj(object_id: Literal[3603]) -> td.SfxType: ...
@overload
def new_obj(object_id: Literal[3604]) -> td.EventType: ...
@overload
def new_obj(object_id: Literal[3605]) -> td.SongType: ...
@overload
def new_obj(object_id: Literal[3606]) -> td.TriggerType: ...
@overload
def new_obj(object_id: Literal[3607]) -> td.SequenceType: ...
@overload
def new_obj(object_id: Literal[3608]) -> td.SpawnParticleType: ...
@overload
def new_obj(object_id: Literal[3609]) -> td.InstantCollisionType: ...
@overload
def new_obj(object_id: Literal[3612]) -> td.MgSpeedType: ...
@overload
def new_obj(object_id: Literal[3613]) -> td.UiType: ...
@overload
def new_obj(object_id: Literal[3614]) -> td.TimeType: ...
@overload
def new_obj(object_id: Literal[3615]) -> td.TimeEventType: ...
@overload
def new_obj(object_id: Literal[3617]) -> td.TimeControlType: ...
@overload
def new_obj(object_id: Literal[3618]) -> td.ResetType: ...
@overload
def new_obj(object_id: Literal[3619]) -> td.ItemEditType: ...
@overload
def new_obj(object_id: Literal[3620]) -> td.ItemCompareType: ...
@overload
def new_obj(object_id: Literal[3640]) -> td.StateBlockType: ...
@overload
def new_obj(object_id: Literal[3641]) -> td.ItemPersistType: ...
@overload
def new_obj(object_id: Literal[3642]) -> td.BpmType: ...
@overload
def new_obj(object_id: Literal[3643]) -> td.ToggleBlockType: ...
@overload
def new_obj(object_id: Literal[3645]) -> td.ForceBlockType: ...
@overload
def new_obj(object_id: Literal[3660]) -> td.EditAdvFollowType: ...
@overload
def new_obj(object_id: Literal[3661]) -> td.EditAdvFollowType: ...
@overload
def new_obj(object_id: Literal[3662]) -> td.LinkVisibleType: ...
@overload
def new_obj(object_id: Literal[4211]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[4300]) -> td.AnimatedType: ...
@overload
def new_obj(object_id: Literal[4401]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4402]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4403]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4404]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4405]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4406]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4407]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4408]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4409]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4410]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4411]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4412]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4413]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4414]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4415]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4416]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4417]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4418]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4419]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4420]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4421]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4422]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4423]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4424]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4425]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4426]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4427]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4428]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4429]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4430]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4431]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4432]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4433]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4434]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4435]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4436]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4437]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4438]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4439]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4440]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4441]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4442]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4443]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4444]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4445]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4446]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4447]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4448]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4449]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4450]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4451]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4452]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4453]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4454]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4455]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4456]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4457]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4458]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4459]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4460]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4461]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4462]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4463]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4464]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4465]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4466]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4467]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4468]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4469]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4470]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4471]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4472]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4473]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4474]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4475]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4476]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4477]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4478]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4479]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4480]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4481]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4482]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4483]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4484]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4485]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4486]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4487]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4488]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4489]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4490]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4491]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4492]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4493]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4494]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4495]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4496]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4497]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4498]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4499]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4500]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4501]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4502]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4503]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4504]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4505]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4506]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4507]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4508]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4509]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4510]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4511]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4512]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4513]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4514]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4515]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4516]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4517]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4518]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4519]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4520]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4521]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4522]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4523]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4524]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4525]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4526]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4527]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4528]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4529]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4530]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4531]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4532]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4533]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4534]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4535]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4536]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4537]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4538]) -> td.CollectibleType: ...
@overload
def new_obj(object_id: Literal[4539]) -> td.CollectibleType: ...
def new_obj(object_id: int) -> ObjectType: ...