"""Object TypedDict definitions"""

# IMPORTANT: the 'a' suffix is a workaround for type safety.
# 
# These types are autogenerated through a 3 step process. 
# Read build_tools for autogeneration scripts
